# ======================================================================================================================================
trigger: none

pool:
  vmImage: 'Ubuntu-20.04'

variables:
- group: VARGRPTEMP 


resources:
  repositories:
    - repository: templates
      type: git
      name: terraform_infra_template
      ref:  master

stages:
- template: infra-terraform-templates/lint.yml@templates  # Template reference si utilise dans un autre repos mettre le path suivant jobs/lint.yml@templates
  parameters:
    terraformFolder: $(terraformFolder)
    vmImage: $(vmImage)

# validate terraform
- template: infra-terraform-templates/validate.yml@templates  # Template reference si utilise dans un autre repos mettre le path suivant jobs/build.yml@templates
  parameters:
    terraformFolder: $(terraformFolder)
    terraformVersion: $(terraformVersion)
    AZURE_SERVICE_CONNECTION_NAME: $(AZURE_SERVICE_CONNECTION_NAME)
    RESOURCE_GROUP_NAME: $(RESOURCE_GROUP_NAME)
    STORAGE_ACCOUNT_NAME: $(STORAGE_ACCOUNT_NAME)
    CONTAINER_NAME: $(CONTAINER_NAME)
    KEY_DEV: $(KEY_DEV)
    KEY_VAL: $(KEY_VAL)
    KEY_PRD: $(KEY_PRD)
    vmImage: $(vmImage)

    
- template: infra-terraform-templates/build.yml@templates  # Template reference si utilise dans un autre repos mettre le path suivant jobs/deploy.yml@templates
  parameters:
    terraformFolder: $(terraformFolder)
    terraformVersion: $(terraformVersion)
    commandOptions: $(commandOptions)
    AZURE_SERVICE_CONNECTION_NAME: $(AZURE_SERVICE_CONNECTION_NAME)
    RESOURCE_GROUP_NAME: $(RESOURCE_GROUP_NAME)
    STORAGE_ACCOUNT_NAME: $(STORAGE_ACCOUNT_NAME)
    CONTAINER_NAME: $(CONTAINER_NAME)
    KEY_DEV: $(KEY_DEV)
    KEY_VAL: $(KEY_VAL)
    KEY_PRD: $(KEY_PRD)
    vmImage: $(vmImage)


- template: infra-terraform-templates/deploy.yml@templates  # Template reference si utilise dans un autre repos mettre le path suivant jobs/deploy.yml@templates
  parameters:
    terraformFolder: $(terraformFolder)
    terraformVersion: $(terraformVersion)
    commandOptions: $(commandOptions)
    AZURE_SERVICE_CONNECTION_NAME: $(AZURE_SERVICE_CONNECTION_NAME)
    RESOURCE_GROUP_NAME: $(RESOURCE_GROUP_NAME)
    STORAGE_ACCOUNT_NAME: $(STORAGE_ACCOUNT_NAME)
    CONTAINER_NAME: $(CONTAINER_NAME)
    KEY_DEV: $(KEY_DEV)
    KEY_VAL: $(KEY_VAL)
    vmImage: $(vmImage)
 

- template: infra-terraform-templates/deploy_prd.yml@templates  # Template reference si utilise dans un autre repos mettre le path suivant jobs/deploy.yml@templates
  parameters:
    terraformFolder: $(terraformFolder)
    terraformVersion: $(terraformVersion)
    commandOptions: $(commandOptions)
    AZURE_SERVICE_CONNECTION_NAME: $(AZURE_SERVICE_CONNECTION_NAME)
    RESOURCE_GROUP_NAME: $(RESOURCE_GROUP_NAME)
    STORAGE_ACCOUNT_NAME: $(STORAGE_ACCOUNT_NAME)
    CONTAINER_NAME: $(CONTAINER_NAME)
    KEY_PRD: $(KEY_PRD)
    vmImage: $(vmImage)